language: rust
rust:
  - stable
cache: cargo
os: linux
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - sourceline: ppa:kirillshkrogalev/ffmpeg-next
      - sourceline: ppa:obsproject/obs-studio
    packages:
      - obs-studio
script:
  - cargo build --verbose --all
