[package]
name = "obs-gpmdp"
version = "0.1.0"
authors = ["Matthew Donoughe <mdonoughe@gmail.com>"]

[lib]
name = "gpmdp"
crate-type = ["dylib"]

[dependencies]
futures = "0.1.18"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1.12"
websocket = "0.20.2"