[package]
name = "libobs-sys"
version = "0.1.0"
authors = ["Matthew Donoughe <mdonoughe@gmail.com>"]
links = "obs"
build = "build.rs"

[lib]

[build-dependencies]
bindgen = "0.36"

[target.'cfg(windows)'.build-dependencies]
cc = "1.0"
regex = "1.0"
winreg = "0.5"
